[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "functions"
  publish = "public"
